#!/usr/bin/env python3
"""Generate compact C++ species lookup tables from YoKaiWatchBank data."""

from __future__ import annotations

import importlib.util
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / "yokai-watch-bank"
OUT = ROOT / "common" / "source" / "yokai" / "Species.cpp"


def cpp(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_yw1() -> dict[int, str]:
    path = SOURCE / "vendor" / "yw_save" / "yw1_dump.py"
    spec = importlib.util.spec_from_file_location("yw1_dump", path)
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load YW1 table")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return dict(module.youkai)


def load_xml(name: str) -> dict[int, str]:
    root = ET.parse(SOURCE / "data" / name).getroot()
    return {int(item.attrib["id"]): item.attrib["name"] for item in root}


def main() -> None:
    tables = {
        "yw1": load_yw1(),
        "yw2": load_xml("yw2_species.xml"),
        "yw3": load_xml("yw3_species.xml"),
        "blasters": load_xml("blasters_species.xml"),
        "busters2": load_xml("busters2_species.xml"),
    }
    move_tables = {
        "blastersMoves": json.loads((SOURCE / "data" / "blasters_technic.json").read_text()),
        "busters2Moves": json.loads((SOURCE / "data" / "busters2_technic.json").read_text()),
    }
    lines = [
        "/* Generated by tools/generate_yokai_tables.py. GPL-3.0-or-later. */",
        '#include "yokai/Species.hpp"',
        "#include <algorithm>",
        "#include <array>",
        "#include <cctype>",
        "#include <span>",
        "#include <string>",
        "",
        "namespace yokai",
        "{",
        "    namespace",
        "    {",
        "        struct SpeciesEntry { std::uint32_t id; std::string_view name; };",
    ]
    for key, table in tables.items():
        entries = sorted(((ident & 0xFFFFFFFF, name) for ident, name in table.items()))
        lines.append(f"        constexpr std::array<SpeciesEntry, {len(entries)}> {key} = {{{{")
        lines.extend(f"            {{{ident}, {cpp(name)}}}," for ident, name in entries)
        lines.append("        }};")
    lines.append("        struct MoveEntry { std::uint32_t id; std::array<std::uint32_t, 3> moves; std::uint8_t count; };")
    for key, table in move_tables.items():
        entries = sorted((int(ident), moves[:3]) for ident, moves in table.items())
        lines.append(f"        constexpr std::array<MoveEntry, {len(entries)}> {key} = {{{{")
        for ident, moves in entries:
            padded = moves + [0] * (3 - len(moves))
            lines.append(
                f"            {{{ident}, {{{padded[0]}, {padded[1]}, {padded[2]}}}, {len(moves)}}},"
            )
        lines.append("        }};")
    lines.extend(
        [
            "",
            "        template <std::size_t N>",
            "        std::span<const SpeciesEntry> asSpan(const std::array<SpeciesEntry, N>& value)",
            "        { return value; }",
            "",
            "        std::span<const SpeciesEntry> table(Game game)",
            "        {",
            "            switch (game)",
            "            {",
            "                case Game::YW1: return asSpan(yw1);",
            "                case Game::YW2: return asSpan(yw2);",
            "                case Game::YW3: return asSpan(yw3);",
            "                case Game::Blasters: return asSpan(blasters);",
            "                case Game::Busters2: return asSpan(busters2);",
            "            }",
            "            return {};",
            "        }",
            "",
            "        std::string baseName(std::string_view value)",
            "        {",
            "            const std::size_t suffix = value.find(\" (\");",
            "            std::string output(value.substr(0, suffix));",
            "            std::transform(output.begin(), output.end(), output.begin(),",
            "                [](unsigned char c) { return static_cast<char>(std::tolower(c)); });",
            "            return output;",
            "        }",
            "    }",
            "",
            "    std::string_view speciesName(Game game, std::uint32_t id)",
            "    {",
            "        const auto entries = table(game);",
            "        const auto found = std::lower_bound(entries.begin(), entries.end(), id,",
            "            [](const SpeciesEntry& entry, std::uint32_t wanted) { return entry.id < wanted; });",
            "        return found != entries.end() && found->id == id ? found->name : std::string_view{};",
            "    }",
            "",
            "    std::optional<std::uint32_t> speciesId(Game game, std::string_view name)",
            "    {",
            "        std::optional<std::uint32_t> result;",
            "        for (const SpeciesEntry& entry : table(game))",
            "            if (entry.name == name) result = entry.id;",
            "        return result;",
            "    }",
            "",
            "    std::optional<std::uint32_t> transferSpeciesId(",
            "        Game source, Game target, std::string_view name)",
            "    {",
            "        if (const auto exact = speciesId(target, name)) return exact;",
            "        const auto sourceId = speciesId(source, name);",
            "        if (!sourceId) return std::nullopt;",
            "        const std::string_view candidate = speciesName(target, *sourceId);",
            "        if (!candidate.empty() && baseName(candidate) == baseName(name)) return sourceId;",
            "        return std::nullopt;",
            "    }",
            "",
            "    std::span<const std::uint32_t> defaultMoves(Game game, std::uint32_t id)",
            "    {",
            "        const auto find = [id](const auto& entries) -> std::span<const std::uint32_t>",
            "        {",
            "            const auto item = std::lower_bound(entries.begin(), entries.end(), id,",
            "                [](const MoveEntry& entry, std::uint32_t wanted) { return entry.id < wanted; });",
            "            return item != entries.end() && item->id == id",
            "                ? std::span<const std::uint32_t>(item->moves).first(item->count)",
            "                : std::span<const std::uint32_t>{};",
            "        };",
            "        if (game == Game::Blasters) return find(blastersMoves);",
            "        if (game == Game::Busters2) return find(busters2Moves);",
            "        return {};",
            "    }",
            "}",
            "",
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({sum(map(len, tables.values()))} entries)")


if __name__ == "__main__":
    sys.exit(main())
